# Generated by Django 3.1.6 on 2021-02-07 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitorapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='citizenship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='monitorapp.citizenship'),
        ),
        migrations.AddField(
            model_name='person',
            name='industry',
            field=models.ManyToManyField(null=True, to='monitorapp.Industry', verbose_name='Сфера'),
        ),
    ]
