# Generated by Django 3.1.6 on 2021-02-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorapp', '0002_auto_20210207_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='industry',
            field=models.ManyToManyField(blank=True, to='monitorapp.Industry', verbose_name='Сфера'),
        ),
    ]
