# Generated by Django 3.1.6 on 2021-02-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorapp', '0005_remove_person_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='industry',
            field=models.ManyToManyField(to='monitorapp.Industry', verbose_name='Сфера'),
        ),
    ]
