# Generated by Django 3.1.6 on 2021-02-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorapp', '0007_auto_20210207_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='air',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='cocain',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='doshirak',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='falcon',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='iphone',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='janitor',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='krepost',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='lenin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='palace',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='rub',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='tesla',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='weed',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
